version: '3.8'

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

services:

  frontend:
    image: askzg-frontend:latest
    ports:
      - "8090:80"
    restart: on-failure
    networks:
      - app-network

  backend:
    image: askzg-backend:latest
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - path: .backend.env
        required: true

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: dev-postgres
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "askzgdb"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    env_file:
      - path: .db.env
        required: true
