version: '3.8'

volumes:
  postgres_data:

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: dev-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=askzgdb
